name: Deploy Pre-built Artifacts to Vercel

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  Deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./salon-frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Override Commit Author for Vercel
        run: |
          git config user.name "Deployment Bot"
          git config user.email "${{ secrets.VERCEL_OWNER_EMAIL }}"
          git commit --amend --no-edit --author="Deployment Bot <${{ secrets.VERCEL_OWNER_EMAIL }}>"

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Build Project Artifacts
        run: vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy Pre-built Artifacts
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN